### ISSUE TITLE
Built index.html lags behind injected index.html

### ISSUE THREAD

**Issue by ZakTax** [ali322/inject-html-webpack-plugin#2]
When I build my app, the plugin works but the built index.html lags behind the injected index.html source

For example, using the settings below, when I build my app at 12:00PM, the built index.html will have `<html lang="en">` in `build/index.html` even though `./app/index.html` will have the correctly injected html `<html lang="en" version="12:00PM">`.

If I build again at 12:05PM, `build/index.html` will have `<html lang="en" version="12:00PM">`, not `<html lang="en" version="12:05PM">` (`./app/index.html` will have the correctly injected html `<html lang="en" version="12:05PM">`.

Am I doing something wrong? I can't change my `filename` to `build/index.html` because the build process strips out comments and thus there's no injection point. What can I do to correctly attach version #'s?

`webpack config`
```
new InjectHtmlPlugin({
      filename: './app/index.html',
      customInject: [{
        start: '<!-- start:version-number -->',
        end: '<!-- end:version-number -->',
        content: `<html lang="en" version="${moment().format('MMMM Do YYYY, h:mm:ss a')}">`,
      }],
    }),
```
`./app/index.html`
```
<!-- start:version-number -->
<html lang="en">
<!-- end:version-number -->
```

**Comment by ali322** [comment]
upgrade to latest version.if u supply `output` option,then will inject into the `output` file,otherwise inject into the `filename` file,is it clear?
