### ISSUE TITLE
Way to inject at bottom of template while rewriting URLs

### ISSUE THREAD

**Issue by HoneyryderChuck** [ali322/inject-html-webpack-plugin#3]
I'm currently using [sw cache plugin to load the sw cache worker](https://github.com/goldhand/sw-precache-webpack-plugin). I'm following the instructions there (copy the snippet to the bottom of the page:

```html
 <script>
	if ('serviceWorker' in navigator) {
		 navigator.serviceWorker
			  .register("/sw-cache.js")
			  .then(function() {
			      console.log('Service worker registered!');
			  })
			  .catch(function(error) {
			      console.log('Error registering service worker: ', error);
			  });
	} 
</script>
```

which is fine, but doesn't take advantage of contenthash resource names from webpack. Now, creating the fingerprint sw cache is easy, injecting it in the template is not. Is there a way to inject all of this text to the bottom of my template **while** rewriting the `"/sw-cache-js"` path?

**Comment by ali322** [comment]
use the custom inject feature
