### ISSUE TITLE
Processor?

### ISSUE THREAD

**Issue by sarink** [ali322/inject-html-webpack-plugin#4]
What does `processor` do? It is not described in the readme

**Comment by ali322** [comment]
it has changed to transducer

**Comment by SassNinja** [comment]
> it has changed to transducer – @ali322 

On npmjs.com it still shows `processor` in the description (also confused me)
https://www.npmjs.com/package/inject-html-webpack-plugin

Would you mind to update / publish?

(nice plugin btw – just what I needed)
