### ISSUE TITLE
use publicPath

### ISSUE THREAD

**Issue by SassNinja** [ali322/inject-html-webpack-plugin#5]
I've used multiple instances of your plugin and always need to set my publicPath via the `transducer` option.

What do you think about considering the publicPath of the webpack config and use it if `transducer` is not set?

**Comment by ethikz** [comment]
@SassNinja Are you still wanting this?

I have found a need to allow for an array of files so I had to modify the plugin.  It doesn't seem it is really active, if it's something you would like let me know and I can link you to the package and I can add it or you can submit a PR.

**Comment by SassNinja** [comment]
> and I can link you to the package and I can add it

@ethikz what do you mean with `package`? your fork of this plugin?

The answer to your question is yes, would still be a nice feature.
However I'm thinking about writing an own injection plugin because I need much more options for the injection (e.g. defining the order or support of setting `media` attribute of the injected CSS link)

**Comment by ethikz** [comment]
@SassNinja Yes the plugin.  I've forked it and started working on the feature I need, which is done I just need to add the test for it for the time being.  However if you've already started I can just submit PR's to yours if you'd like?

**Comment by SassNinja** [comment]
> However if you've already started I can just submit PR's to yours if you'd like?

Not started yet (no time at the moment)

But if you like I may inform you once I'm done so you can check if it suits your use cases, too (reviewers are always welcome 😉 )

**Comment by ethikz** [comment]
Ok I've started already and have it working for my use case.  I've scoped it as well.  You can use mine if you'd like, since I've went ahead and updated packages and using es6.

https://github.com/ethikz/inject-html-webpack-plugin
