### ISSUE TITLE
Adding query string to generated script line

### ISSUE THREAD

**Issue by neilicon** [ali322/inject-html-webpack-plugin#8]
I need a way of being able to also add a query string to the generated scripts, to overcome caching issues. 

Would it be possible that when setting up the InjectHtmlPlugin configs I can specify additional query strings that are then added in the html script lines please?  

e.g something similar to the below:

 new InjectHtmlPlugin({ /*this is repeated for each view */
                filename: ....
                processor: ...
                chunks: ...
                queryString: "v=0.1"
            }),

and then it inserts

<script src="...js?v=0.1"></script>

Thanks.

**Comment by ali322** [comment]
you can use transducer as a function
